# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 953aab34b6c415ae741b6cfd392c32e7f0a4b42dbefffaa76912f1bae95e30f3ad6b723db7b0523fa1ff7bdd25b6091d9c126187b75160a42e4918c76bf2879d

test:
  secret_key_base: a446f65f79e240f220a7bd4b662c8f995d5fbb2ce972f985249cce989f9624d9b86490d4fe8d16b02729b17f9689a27399e0080fee7ed3e9b22b5aa1cd476236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
